"""add sprints history

Revision ID: ecdf9d4aa844
Revises: 6eea8de681cb
Create Date: 2026-05-13 10:48:35.557456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecdf9d4aa844'
down_revision: Union[str, None] = '6eea8de681cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprint_num', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('owner_stats_snapshot', sa.JSON(), nullable=False),
    sa.Column('max_sprint_in_jira', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sprints_status_num', 'sprints', ['status', 'sprint_num'], unique=False)
    op.create_table('sprint_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('task_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sprint_tasks_sprint_pos', 'sprint_tasks', ['sprint_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sprint_tasks_sprint_pos', table_name='sprint_tasks')
    op.drop_table('sprint_tasks')
    op.drop_index('ix_sprints_status_num', table_name='sprints')
    op.drop_table('sprints')
    # ### end Alembic commands ###
