"""init configs schema

Revision ID: 6eea8de681cb
Revises: 
Create Date: 2026-05-05 13:10:22.776965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eea8de681cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('project_key', sa.String(length=50), nullable=False),
    sa.Column('sprint_field', sa.String(length=50), nullable=False),
    sa.Column('responsible_field', sa.String(length=50), nullable=False),
    sa.Column('hours_per_person', sa.Float(), nullable=False),
    sa.Column('default_task_hours', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bucket_hours_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=50), nullable=False),
    sa.Column('customfield_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'bucket', name='uq_buckethours_config_bucket')
    )
    op.create_table('config_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('jira_board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'jira_board_id', name='uq_board_config_jiraid')
    )
    op.create_table('config_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'name', name='uq_component_config_name')
    )
    op.create_table('role_hours_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('customfield_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'role', name='uq_rolehours_config_role')
    )
    op.create_table('status_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('jira_status', sa.String(length=100), nullable=False),
    sa.Column('bucket', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'jira_status', name='uq_statusbucket_config_status')
    )
    op.create_table('status_priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('jira_status', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'jira_status', name='uq_statusprio_config_status')
    )
    op.create_table('strict_assignee_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'bucket', name='uq_strict_config_bucket')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('jira_account_id', sa.String(length=100), nullable=False),
    sa.Column('jira_name', sa.String(length=200), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'jira_account_id', name='uq_team_config_account')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members')
    op.drop_table('strict_assignee_buckets')
    op.drop_table('status_priorities')
    op.drop_table('status_buckets')
    op.drop_table('role_hours_fields')
    op.drop_table('config_components')
    op.drop_table('config_boards')
    op.drop_table('bucket_hours_fields')
    op.drop_table('configs')
    # ### end Alembic commands ###
